USE HBTSCustPerf

DECLARE @Startdate date = '2024-01-01'
DECLARE @Enddate date = '2024-08-01'

USE HBTSCustPerf
SELECT TOP 10 (MAX(cust.[Cust Name])) as 'Name'
	,MAX(svc.GROUPER_1) as 'Grouper 1'
	,SUM(svc.SVC_SUCCESSES_FOR_GROUPER) as 'SVC Successes'
	,SUM(svc.SVC_FAILURES_FOR_GROUPER) as 'SVC Failures'
	,SUM(svc.NOT_SVCD_FOR_GROUPER) as 'Not SVCd for Grouper'
	,(100*SUM(svc.SVC_SUCCESSES_FOR_GROUPER) / (SUM(svc.SVC_FAILURES_FOR_GROUPER) + SUM(svc.SVC_SUCCESSES_FOR_GROUPER) + SUM(svc.NOT_SVCD_FOR_GROUPER))) as 'SVC Success %'
	--,CASE
FROM [rc].[SVC_ONEPAGER] as svc
	JOIN [rc].V_TS_TO_CUST as cust
	on svc.OID = cust.OID
WHERE svc.GROUPER_1 = 'GI'
	AND svc.METRIC_START_DATE >= @Startdate
	AND svc.METRIC_END_DATE <= @Enddate
GROUP BY cust.[Cust Name]
HAVING (100*SUM(svc.SVC_SUCCESSES_FOR_GROUPER) / (SUM(svc.SVC_FAILURES_FOR_GROUPER) + SUM(svc.SVC_SUCCESSES_FOR_GROUPER) + SUM(svc.NOT_SVCD_FOR_GROUPER))) > 0
	AND SUM(svc.SVC_SUCCESSES_FOR_GROUPER) / NULLIF((SUM(svc.SVC_FAILURES_FOR_GROUPER) + SUM(svc.SVC_SUCCESSES_FOR_GROUPER) + SUM(svc.NOT_SVCD_FOR_GROUPER)), 0) *100 > 90
ORDER BY 'SVC Successes' DESC;